services:
  - docker

before_install:
- docker pull base/archlinux:latest

script:
- ls
- docker -v $(pwd):/repo -v $(pwd)/tmp:/pkgtmp run base/archlinux:latest /bin/sh -c "cp -R /repo /pkgtmp && makepkg -s && useradd -u 1000 -d /home/makepkg -m makepkg && chown -R makepkg /work /home/makepkg && pacman -Syu --noconfirm && su -l makepkg -c 'git config --global user.name Make Pkg' && su -l makepkg -c 'git config --global user.email example@example.com' && su -l makepkg -c 'cd /pkgtmp && makepkg --noconfirm -si && mksrcinfo'"
- ls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: tmp
  on:
    branch: master
